import Testing
import Foundation
import AppKit
@testable import PushTextKit

/// The suite's one and only pasteboard, fetched from the server exactly once (#234).
///
/// **Why one.** `NSPasteboard(name:)` reaches the pasteboard server over mach, and on a headless CI
/// runner that server is intermittently unresponsive - the #144 wedge, bounded but not cured by
/// #179. Each test used to take its OWN named board, so Swift Testing's parallelism fired seven
/// concurrent acquisitions at a serial setup path. Run 33174982445 shows the cost: four returned and
/// the other three all timed out at the same instant, on a docs-only PR whose Swift sources were
/// byte-identical to a green master run two minutes earlier.
///
/// Whether that concurrency CAUSES the stall is correlation, not a verified cause - the wedge does
/// not reproduce on a Mac with a live window server, so there is no local red to turn green. What is
/// verifiable is the exposure, and one acquisition is strictly less of it than seven.
///
/// **Still NAMED, never `.general`.** A test that scribbles on the real clipboard destroys whatever
/// the developer had copied, on every run. The name was never the problem.
///
/// **No retry.** A second attempt against a stalled mach send re-hangs and abandons another thread,
/// and the four acquisitions that returned are not evidence that a fifth would. If this one stalls,
/// `BoundedWork` says so within ten seconds and the suite fails honestly.
///
/// **What keeps it at one is `.engine/checks/one-test-pasteboard.sh`, not a test.** The obvious
/// runtime guard - count the acquisitions, assert 1 - was written first and PLANTED AGAINST, and it
/// passed on the broken version: with the suite serialized, the counting test ran first and saw only
/// its own acquisition. An assertion whose verdict depends on execution order cannot say no, so it
/// was replaced by a source gate that counts acquisition SITES and does not care when they run.
private final class SharedPasteboard: @unchecked Sendable {
    static let shared = SharedPasteboard()

    private let result: Result<NSPasteboard, any Error>

    private init() {
        let name = NSPasteboard.Name("dev.ecn.apps.pushtext.test.shared")
        result = Result {
            try BoundedWork.run("NSPasteboard(name: \(name.rawValue))", timeout: 10) {
                NSPasteboard(name: name)
            }
        }
    }

    func board() throws -> NSPasteboard { try result.get() }
}

/// Keeps dictated text out of third-party clipboard managers (#41).
///
/// Every utterance passes through `NSPasteboard.general`, so Raycast, Maccy, Paste and Alfred will
/// archive it into a searchable, persisted history unless the item is marked. Three of the five
/// surveyed open-source dictation apps set these markers; the research calls their absence in
/// OpenSuperWhisper "a privacy bug" (docs/research/04 sec 3.7). For an app whose entire pitch is
/// that nothing leaves the machine, text landing in a third-party archive contradicts the product
/// claim rather than merely being untidy.
///
/// `.serialized` is load-bearing rather than tidiness: these tests share one pasteboard, and run in
/// parallel they would overwrite each other's contents between the write and the read.
@Suite("Pasteboard conceal markers", .serialized)
struct PasteboardMarkersTests {

    private func pasteboard() throws -> NSPasteboard { try SharedPasteboard.shared.board() }

    @Test("The staged item carries the text itself")
    func stagesTheText() throws {
        let pasteboard = try pasteboard()
        PasteboardTextInjector.stage("hello world", on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "hello world")
    }

    @Test("The staged item is marked transient, concealed and auto-generated")
    func stagesAllThreeMarkers() throws {
        let pasteboard = try pasteboard()
        PasteboardTextInjector.stage("secret dictation", on: pasteboard)

        let types = pasteboard.pasteboardItems?.first?.types.map(\.rawValue) ?? []
        for marker in ["org.nspasteboard.TransientType",
                       "org.nspasteboard.ConcealedType",
                       "org.nspasteboard.AutoGeneratedType"] {
            #expect(types.contains(marker), "missing \(marker); item had \(types)")
        }
    }

    /// The markers must ride on the SAME item as the text. A clipboard manager reads the item it is
    /// about to archive - a marker on a sibling item would be invisible to it, and the check above
    /// would still pass if the two were split.
    @Test("The markers are on the same item as the text, not a sibling")
    func markersRideWithTheText() throws {
        let pasteboard = try pasteboard()
        PasteboardTextInjector.stage("hello", on: pasteboard)

        let items = pasteboard.pasteboardItems ?? []
        #expect(items.count == 1, "expected exactly one item, got \(items.count)")

        let item = items.first
        #expect(item?.string(forType: .string) == "hello")
        #expect(item?.types.map(\.rawValue).contains("org.nspasteboard.ConcealedType") == true)
    }

    @Test("Staging replaces previous contents rather than appending to them")
    func stagingReplaces() throws {
        let pasteboard = try pasteboard()
        pasteboard.clearContents()
        pasteboard.setString("something the user copied", forType: .string)

        PasteboardTextInjector.stage("dictated", on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "dictated")
        #expect((pasteboard.pasteboardItems ?? []).count == 1)
    }

    /// `changeCount` is what `ClipboardRestore` compares against to decide whether anyone else took
    /// the clipboard while we were pasting. Staging has to bump it, or that guard reads every
    /// injection as a foreign write and the user's clipboard is never restored.
    @Test("Staging bumps the change count, which the restore guard depends on")
    func stagingBumpsChangeCount() throws {
        let pasteboard = try pasteboard()
        let before = pasteboard.changeCount

        let after = PasteboardTextInjector.stage("dictated", on: pasteboard)

        #expect(after > before)
        #expect(after == pasteboard.changeCount)
    }
}

extension PasteboardMarkersTests {

    /// An explicit COPY is the opposite intent to an injection (#106).
    ///
    /// `stage` marks dictated text transient/concealed so a clipboard manager will not archive it -
    /// correct, because the user never asked for that text to enter their clipboard history. A user
    /// who presses a copy button is asking for exactly that, and reusing `stage` would hand them
    /// text their own clipboard manager is instructed to discard: a button that appears to work and
    /// silently does not.
    @Test("Copying for the user writes plain, UNMARKED text")
    func copyIsNotConcealed() throws {
        let pasteboard = try pasteboard()
        PasteboardTextInjector.copy("keep this one", on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "keep this one")

        let types = pasteboard.pasteboardItems?.first?.types.map(\.rawValue) ?? []
        for marker in PasteboardTextInjector.concealMarkers.map(\.rawValue) {
            #expect(!types.contains(marker),
                    "copy must not conceal: found \(marker) in \(types)")
        }
    }

    /// The discriminator. Both write the same string, so asserting only on the text would pass with
    /// `copy` implemented as a call to `stage` - which is the mistake worth preventing.
    ///
    /// One board written twice rather than two boards written once (#234). Same comparison, half the
    /// server round trips, and it removes a confound: any difference now has to come from the two
    /// calls rather than from two separately created pasteboards.
    @Test("Copy and inject differ in exactly the markers")
    func copyAndStageDifferOnlyInMarkers() throws {
        let pasteboard = try pasteboard()

        PasteboardTextInjector.copy("same text", on: pasteboard)
        let copiedText = pasteboard.string(forType: .string)
        let copiedTypes = Set(pasteboard.pasteboardItems?.first?.types.map(\.rawValue) ?? [])

        PasteboardTextInjector.stage("same text", on: pasteboard)
        let stagedText = pasteboard.string(forType: .string)
        let stagedTypes = Set(pasteboard.pasteboardItems?.first?.types.map(\.rawValue) ?? [])

        // An unreadable board would make the subtraction below vacuously empty. That is not the
        // marker set, so it still fails - but it would fail for the wrong reason and read as a
        // marker bug, so the emptiness is caught here and named.
        #expect(!copiedTypes.isEmpty, "the copy wrote nothing readable; the comparison is meaningless")
        #expect(copiedText == stagedText)
        #expect(stagedTypes.subtracting(copiedTypes)
                    == Set(PasteboardTextInjector.concealMarkers.map(\.rawValue)),
                "the only difference between them must be the conceal markers")
    }
}
