import Testing
import Foundation
import AppKit
@testable import PushTextKit

/// Keeps dictated text out of third-party clipboard managers (#41).
///
/// Every utterance passes through `NSPasteboard.general`, so Raycast, Maccy, Paste and Alfred will
/// archive it into a searchable, persisted history unless the item is marked. Three of the five
/// surveyed open-source dictation apps set these markers; the research calls their absence in
/// OpenSuperWhisper "a privacy bug" (docs/research/04 sec 3.7). For an app whose entire pitch is
/// that nothing leaves the machine, text landing in a third-party archive contradicts the product
/// claim rather than merely being untidy.
///
/// These use a NAMED pasteboard, never `.general`: a test that scribbles on the real clipboard
/// destroys whatever the developer had copied, and would do it on every run.
@Suite("Pasteboard conceal markers")
struct PasteboardMarkersTests {

    private func makePasteboard(_ label: String) -> NSPasteboard {
        NSPasteboard(name: NSPasteboard.Name("dev.ecn.apps.pushtext.test.\(label)"))
    }

    @Test("The staged item carries the text itself")
    func stagesTheText() {
        let pasteboard = makePasteboard("text")
        PasteboardTextInjector.stage("hello world", on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "hello world")
    }

    @Test("The staged item is marked transient, concealed and auto-generated")
    func stagesAllThreeMarkers() {
        let pasteboard = makePasteboard("markers")
        PasteboardTextInjector.stage("secret dictation", on: pasteboard)

        let types = pasteboard.pasteboardItems?.first?.types.map(\.rawValue) ?? []
        for marker in ["org.nspasteboard.TransientType",
                       "org.nspasteboard.ConcealedType",
                       "org.nspasteboard.AutoGeneratedType"] {
            #expect(types.contains(marker), "missing \(marker); item had \(types)")
        }
    }

    /// The markers must ride on the SAME item as the text. A clipboard manager reads the item it is
    /// about to archive - a marker on a sibling item would be invisible to it, and the check above
    /// would still pass if the two were split.
    @Test("The markers are on the same item as the text, not a sibling")
    func markersRideWithTheText() {
        let pasteboard = makePasteboard("sameitem")
        PasteboardTextInjector.stage("hello", on: pasteboard)

        let items = pasteboard.pasteboardItems ?? []
        #expect(items.count == 1, "expected exactly one item, got \(items.count)")

        let item = items.first
        #expect(item?.string(forType: .string) == "hello")
        #expect(item?.types.map(\.rawValue).contains("org.nspasteboard.ConcealedType") == true)
    }

    @Test("Staging replaces previous contents rather than appending to them")
    func stagingReplaces() {
        let pasteboard = makePasteboard("replace")
        pasteboard.clearContents()
        pasteboard.setString("something the user copied", forType: .string)

        PasteboardTextInjector.stage("dictated", on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "dictated")
        #expect((pasteboard.pasteboardItems ?? []).count == 1)
    }

    /// `changeCount` is what `ClipboardRestore` compares against to decide whether anyone else took
    /// the clipboard while we were pasting. Staging has to bump it, or that guard reads every
    /// injection as a foreign write and the user's clipboard is never restored.
    @Test("Staging bumps the change count, which the restore guard depends on")
    func stagingBumpsChangeCount() {
        let pasteboard = makePasteboard("changecount")
        let before = pasteboard.changeCount

        let after = PasteboardTextInjector.stage("dictated", on: pasteboard)

        #expect(after > before)
        #expect(after == pasteboard.changeCount)
    }
}

extension PasteboardMarkersTests {

    /// An explicit COPY is the opposite intent to an injection (#106).
    ///
    /// `stage` marks dictated text transient/concealed so a clipboard manager will not archive it -
    /// correct, because the user never asked for that text to enter their clipboard history. A user
    /// who presses a copy button is asking for exactly that, and reusing `stage` would hand them
    /// text their own clipboard manager is instructed to discard: a button that appears to work and
    /// silently does not.
    @Test("Copying for the user writes plain, UNMARKED text")
    func copyIsNotConcealed() {
        let pasteboard = makePasteboard("copy")
        PasteboardTextInjector.copy("keep this one", on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "keep this one")

        let types = pasteboard.pasteboardItems?.first?.types.map(\.rawValue) ?? []
        for marker in PasteboardTextInjector.concealMarkers.map(\.rawValue) {
            #expect(!types.contains(marker),
                    "copy must not conceal: found \(marker) in \(types)")
        }
    }

    /// The discriminator. Both write the same string, so asserting only on the text would pass with
    /// `copy` implemented as a call to `stage` - which is the mistake worth preventing.
    @Test("Copy and inject differ in exactly the markers")
    func copyAndStageDifferOnlyInMarkers() {
        let copied = makePasteboard("diff-copy")
        let staged = makePasteboard("diff-stage")
        PasteboardTextInjector.copy("same text", on: copied)
        PasteboardTextInjector.stage("same text", on: staged)

        #expect(copied.string(forType: .string) == staged.string(forType: .string))

        let copiedTypes = Set(copied.pasteboardItems?.first?.types.map(\.rawValue) ?? [])
        let stagedTypes = Set(staged.pasteboardItems?.first?.types.map(\.rawValue) ?? [])
        #expect(stagedTypes.subtracting(copiedTypes)
                    == Set(PasteboardTextInjector.concealMarkers.map(\.rawValue)),
                "the only difference between them must be the conceal markers")
    }
}
