#!/usr/bin/env bash
# Conventional Commits, enforced on BOTH inputs the squash header can come from.
#
# This repo squashes with squash_merge_commit_title=COMMIT_OR_PR_TITLE. That setting picks the
# COMMIT subject for a one-commit PR and the PR TITLE for a multi-commit one, so checking either
# alone passes every time you happen to test it on the case it covers. Two subjects on master are
# already non-conventional because of exactly that:
#
#   Publish measured latency numbers and log release-to-text (#65)
#   File backlog as GitHub issues so every citation resolves (#23)
#
# Both came from multi-commit PRs whose commits were conventional and whose TITLES were not. A
# local commit-msg hook could never have caught either.
#
# Locally: validates each commit on this branch that is not on origin/master.
# In CI:   also validates PR_TITLE, passed through the environment rather than interpolated into
#          the shell, since a PR title is attacker-controlled text.
set -euo pipefail

TYPES='feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert'
PATTERN="^($TYPES)(\([a-z0-9._/-]+\))?!?: [A-Z]"

# GitHub appends " (#1234)" to the squash header AFTER the subject has cleared any local hook, so
# the budget has to be reserved here or nothing catches the overflow. Longest on master is 89
# including that suffix.
MAX=84

fail=0

check() {
    local what="$1" subject="$2"
    if [ -z "$subject" ]; then
        echo "conventional-subjects: $what is empty" >&2
        fail=1
        return
    fi
    if ! printf '%s' "$subject" | grep -qE "$PATTERN"; then
        echo "conventional-subjects: $what is not <type>(scope)!: <Capitalized>" >&2
        echo "    $subject" >&2
        fail=1
    fi
    # Characters, not bytes: an em dash is 3 bytes and `wc -c` would score a passing subject over.
    local length
    length="$(printf '%s' "$subject" | wc -m | tr -d ' ')"
    if [ "$length" -gt "$MAX" ]; then
        echo "conventional-subjects: $what is $length chars, over the $MAX budget" >&2
        echo "    (GitHub appends ' (#N)' to the squash header after this point)" >&2
        echo "    $subject" >&2
        fail=1
    fi
}

# `+set`, not `:-`: an UNSET PR_TITLE means a local run with nothing to check, but a SET-BUT-EMPTY
# one means CI asked for a title and got nothing - a broken workflow expression. Treating those the
# same is how a gate ends up passing while checking zero things, which reads identically to green.
if [ -n "${PR_TITLE+set}" ]; then
    check "the PR title" "$PR_TITLE"
fi

base="${BASE_REF:-origin/master}"
if git rev-parse --verify --quiet "$base" >/dev/null; then
    range="$(git merge-base "$base" HEAD)..HEAD"
    while IFS= read -r subject; do
        [ -n "$subject" ] || continue
        # A merge commit's subject is generated by git and is not ours to format.
        case "$subject" in "Merge "*) continue ;; esac
        check "commit subject" "$subject"
    done < <(git log --format="%s" "$range")
else
    echo "conventional-subjects: $base not found; checked the PR title only" >&2
fi

if [ "$fail" -ne 0 ]; then
    echo "conventional-subjects: see CLAUDE.md, Git Commits" >&2
    exit 1
fi
echo "conventional-subjects: OK"
exit 0
